# Generated by Django 3.2.3 on 2021-05-26 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task',
            field=models.CharField(default=django.utils.timezone.now, max_length=280),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
